[package]
name = "year2025"
version = "0.1.0"
edition = "2024"

[dependencies]
common.path = "../common"
good_lp = { version = "*", features = ["scip", "scip_bundled"], default-features = false }

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "my_benchmark"
harness = false