[package]
name = "year2022"
version = "0.1.0"
edition = "2024"

[dependencies]
common.path = "../common"

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "my_benchmark"
harness = false
